GROUPIDPREFIX=$1;
GROUPIDSUFFIX=$2;
GROUPID=$GROUPIDPREFIX.$GROUPIDSUFFIX;
PARENTFOLDER=releng/$GROUPID.parent;
PARENTPOM=$PARENTFOLDER/pom.xml;
AGGREGATORFOLDER=releng/$GROUPID.aggregator;
AGGREGATORPOM=$AGGREGATORFOLDER/pom.xml;
UPDATESITEFOLDER=releng/$GROUPID.updatesite;
UPDATEPOM=$UPDATESITEFOLDER/pom.xml
BUNDLEFOLDER=bundles;
BUNDLEPOM=$BUNDLEFOLDER/pom.xml;
mkdir tests;
mkdir features;
mkdir -p $PARENTFOLDER;
cp parent_TEMPLATE.pom $PARENTPOM;
sed -i 's/theGroupID/'$GROUPID'/g' $PARENTPOM;
mkdir -p $AGGREGATORFOLDER;
cp aggregator_TEMPLATE.pom $AGGREGATORPOM;
sed -i 's/theGroupID/'$GROUPID'/g' $AGGREGATORPOM;
mkdir -p $UPDATESITEFOLDER;
cp updatesite_TEMPLATE.pom $UPDATEPOM;
sed -i 's/theSuffixOfTheGroupID/'$GROUPIDSUFFIX'/g' $UPDATEPOM;
sed -i 's/theGroupID/'$GROUPID'/g' $UPDATEPOM;
mkdir .mvn;
cp extensions.xml .mvn/;
mkdir $BUNDLEFOLDER;
cp bundle_TEMPLATE.pom $BUNDLEPOM;
sed -i 's/thePrefixOfTheGroupID/'$GROUPIDPREFIX'/g' $BUNDLEPOM;
sed -i 's/theGroupID/'$GROUPID'/g' $BUNDLEPOM;
git add tests features releng pom.xml .mvn bundles/pom.xml;